apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap-logwise-config.yaml
  - secret-aws.yaml
  - secret-db-orch.yaml
  - secret-db-grafana.yaml
  - kafka/kafka.yaml
  - spark/spark-master.yaml
  - spark/spark-worker.yaml
  - otel/otel-collector.yaml
  - vector/vector.yaml
  - mysql/orch-mysql-init-configmap.yaml
  - mysql/orch-mysql.yaml
  - orchestrator/orchestrator.yaml
  - mysql/grafana-mysql.yaml
  - grafana/grafana.yaml
  - cron/cron-orchestrator-sync.yaml
  - healthcheck/healthcheck-dummy.yaml


